"use client";

import { ArrowRight } from "lucide-react";
import type { Workflow } from "@/lib/workflows";

const dmSerif = { fontFamily: "var(--font-dm-serif), serif", fontStyle: "italic" as const };
const dmSans = { fontFamily: "var(--font-dm-sans), sans-serif" };

// Path 1 outcome — a recommended library template plus two CTAs.
// Compact preview rather than the full butterfly card so the user can
// decide quickly without scrolling. They get the full view by clicking
// "Adapt this" (lands on canvas) or "Show me other templates" (opens
// the Library).
export function PathRecommendation({
  workflow,
  rationale,
  onAdapt,
  onBrowseLibrary,
}: {
  workflow: Workflow;
  // One-line plain-language reason this template was picked. Already
  // generated by the upstream caller; we just render it.
  rationale: string;
  onAdapt: () => void;
  onBrowseLibrary: () => void;
}) {
  const stepCount = workflow.steps.length;
  return (
    <div className="magicus-chat-appear" style={{ ...dmSans }}>
      <div
        style={{
          ...dmSerif,
          fontSize: 22,
          color: "#3B4953",
          lineHeight: 1.25,
          marginBottom: 4,
        }}
      >
        Here&apos;s where we&apos;d suggest starting
      </div>
      <p
        style={{
          fontSize: 13,
          color: "#90AB8B",
          lineHeight: 1.5,
          marginBottom: 14,
        }}
      >
        {rationale}
      </p>

      <div
        style={{
          background: "#FFFFFF",
          border: "1px solid #EBF4DD",
          borderRadius: 12,
          padding: "16px 18px",
          marginBottom: 14,
        }}
      >
        <div
          style={{
            ...dmSerif,
            fontSize: 18,
            color: "#3B4953",
            lineHeight: 1.25,
            marginBottom: 6,
          }}
        >
          {workflow.name}
        </div>
        <div
          style={{
            fontSize: 13,
            color: "#547863",
            lineHeight: 1.5,
            marginBottom: 10,
          }}
        >
          {workflow.why}
        </div>
        <div
          style={{
            display: "flex",
            gap: 10,
            fontSize: 11,
            color: "#90AB8B",
            textTransform: "uppercase",
            letterSpacing: 0.6,
          }}
        >
          <span>{stepCount} step{stepCount === 1 ? "" : "s"}</span>
          {workflow.tools.length > 0 && (
            <>
              <span>·</span>
              <span style={{ textTransform: "none", letterSpacing: 0 }}>
                {workflow.tools.slice(0, 3).join(", ")}
                {workflow.tools.length > 3 ? "…" : ""}
              </span>
            </>
          )}
        </div>
      </div>

      <div className="flex items-center gap-2">
        <button
          onClick={onAdapt}
          className="flex items-center gap-2 transition-opacity hover:opacity-90"
          style={{
            background: "#E66B4D",
            color: "#FFFFFF",
            border: "none",
            borderRadius: 999,
            padding: "10px 18px",
            fontSize: 14,
            fontWeight: 500,
            cursor: "pointer",
          }}
        >
          Adapt this to my workflow
          <ArrowRight size={14} />
        </button>
        <button
          onClick={onBrowseLibrary}
          className="hover:bg-[#F7FAF2] transition-colors"
          style={{
            background: "transparent",
            color: "#547863",
            border: "1px solid #547863",
            borderRadius: 999,
            padding: "10px 18px",
            fontSize: 14,
            fontWeight: 500,
            cursor: "pointer",
          }}
        >
          Show me other templates
        </button>
      </div>
    </div>
  );
}
